# sea config
sea:
  list:
    - a
    - b
    - c
  #  @Value方式注入成员
  list2: a,b,c
  #
  host: localhost
  schedule-thread-context-base-package: execution(public * com.abc..*.*(..))
  fastjson:
    enabled: false
  test: SEA_DES()
  base-package: com.abc,com.github.seaxlab
  log:
    enabled: true
    other-base-package: com.abc.service
  web:
    filter:
      enabled: true
      url-pattern: /api/*
      log-mode: 2
