# sea config
sea:
  env: local
  list:
    - a
    - b
    - c
  #  @Value方式注入成员
  list2: a,b,c
  #
  host: localhost
  schedule-thread-context-base-package: execution(public * com.abc..*.*(..))
  fastjson:
    enabled: false
  test: SEA_DES()
  base-package: com.abc,com.github.seaxlab
  log:
    enabled: true
    other-base-package: com.abc.service
  web:
    filter:
      enabled: true
      url-pattern: /api/*
      log-mode: 2
spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://redis:6379"
          database: 1
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"
project:
  order:
    time: 30