server:
  port: 8800

spring:
  profiles:
    active: local
  application:
    name: sea-core-example
logging:
  file: ${spring.application.name}
  path: ${user.home}/logs/${spring.application.name}

sea:
  host: localhost
  env: pro