server:
  port: 8800

spring:
  profiles:
    active: local
  application:
    name: sea-core-example
#  main:
#    lazy-initialization: true
logging:
  file:
    name: ${spring.application.name}
    path: ${user.home}/logs/${spring.application.name}

sea:
  host: localhost
  env: pro
  schedule-thread-context-base-package: execution(public * com.abc..*.*(..))
  fastjson:
    enable: false
  test: SEA_DES()
  base-package: com.abc,com.github.seaxlab
  log:
    enable: true
    other-base-package: com.abc.service
  web:
    filter:
      enable: true
      url-pattern: /api/*