server:
  port: 8800

spring:
  profiles:
    active: local
  application:
    name: sea-core-example2
  cloud:
    nacos:
      discovery:
        register-enabled: false
        server-addr: nacos:8848
    jackson:
      time-zone: GMT+8
logging:
  file:
    name: ${spring.application.name}
    path: ${user.home}/logs/${spring.application.name}